CREATE DATABASE CarsSale;

USE CarsSale

/* ASP.NET Identity */

/****** Object:  Table [dbo].[AspNetRoles]    Script Date: 15-Mar-17 10:27:06 PM ******/

SET ANSI_NULLS ON

GO

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[AspNetRoles](

    [Id] [nvarchar](128) NOT NULL,

    [Name] [nvarchar](256) NOT NULL,

CONSTRAINT [PK_dbo.AspNetRoles] PRIMARY KEY CLUSTERED

(

    [Id] ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

) ON [PRIMARY]



GO

/****** Object:  Table [dbo].[AspNetUserClaims]    Script Date: 15-Mar-17 10:27:06 PM ******/

SET ANSI_NULLS ON

GO

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[AspNetUserClaims](

    [Id] [int] IDENTITY(1,1) NOT NULL,

    [UserId] [nvarchar](128) NOT NULL,

    [ClaimType] [nvarchar](max) NULL,

    [ClaimValue] [nvarchar](max) NULL,

CONSTRAINT [PK_dbo.AspNetUserClaims] PRIMARY KEY CLUSTERED

(

    [Id] ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]



GO

/****** Object:  Table [dbo].[AspNetUserLogins]    Script Date: 15-Mar-17 10:27:06 PM ******/

SET ANSI_NULLS ON

GO

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[AspNetUserLogins](

    [LoginProvider] [nvarchar](128) NOT NULL,

    [ProviderKey] [nvarchar](128) NOT NULL,

    [UserId] [nvarchar](128) NOT NULL,

CONSTRAINT [PK_dbo.AspNetUserLogins] PRIMARY KEY CLUSTERED

(

    [LoginProvider] ASC,

    [ProviderKey] ASC,

    [UserId] ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

) ON [PRIMARY]



GO

/****** Object:  Table [dbo].[AspNetUserRoles]    Script Date: 15-Mar-17 10:27:06 PM ******/

SET ANSI_NULLS ON

GO

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[AspNetUserRoles](

    [UserId] [nvarchar](128) NOT NULL,

    [RoleId] [nvarchar](128) NOT NULL,

CONSTRAINT [PK_dbo.AspNetUserRoles] PRIMARY KEY CLUSTERED

(

    [UserId] ASC,

    [RoleId] ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

) ON [PRIMARY]



GO

/****** Object:  Table [dbo].[AspNetUsers]    Script Date: 15-Mar-17 10:27:06 PM ******/

SET ANSI_NULLS ON

GO

SET QUOTED_IDENTIFIER ON

GO

CREATE TABLE [dbo].[AspNetUsers](

    [Id] [nvarchar](128) NOT NULL,

    [Email] [nvarchar](256) NULL,

    [EmailConfirmed] [bit] NOT NULL,

    [PasswordHash] [nvarchar](max) NULL,

    [SecurityStamp] [nvarchar](max) NULL,

    [PhoneNumber] [nvarchar](max) NULL,

    [PhoneNumberConfirmed] [bit] NOT NULL,

    [TwoFactorEnabled] [bit] NOT NULL,

    [LockoutEndDateUtc] [datetime] NULL,

    [LockoutEnabled] [bit] NOT NULL,

    [AccessFailedCount] [int] NOT NULL,

    [UserName] [nvarchar](256) NOT NULL,

CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED

(

    [Id] ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]



GO

ALTER TABLE [dbo].[AspNetUserClaims]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])

REFERENCES [dbo].[AspNetUsers] ([Id])

ON DELETE CASCADE

GO

ALTER TABLE [dbo].[AspNetUserClaims] CHECK CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId]

GO

ALTER TABLE [dbo].[AspNetUserLogins]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])

REFERENCES [dbo].[AspNetUsers] ([Id])

ON DELETE CASCADE

GO

ALTER TABLE [dbo].[AspNetUserLogins] CHECK CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId]

GO

ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId] FOREIGN KEY([RoleId])

REFERENCES [dbo].[AspNetRoles] ([Id])

ON DELETE CASCADE

GO

ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId]

GO

ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])

REFERENCES [dbo].[AspNetUsers] ([Id])

ON DELETE CASCADE

GO

ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId]

GO

/*******************/


GO

CREATE TABLE [REGION]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(50) UNIQUE NOT NULL,
	PRIMARY KEY ([ID])
);

CREATE TABLE [ROLE]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] nvarchar(10) UNIQUE NOT NULL,
	PRIMARY KEY([ID])
);

CREATE TABLE [USER]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] nvarchar(30) NOT NULL,
	[BIRTHDAY] DATE NOT NULL,
	[PHONE] CHAR(11) UNIQUE NOT NULL,
	[EMAIL] NVARCHAR(50) UNIQUE NOT NULL,
	[PASSWORD] NVARCHAR(32) NOT NULL,
	[LOGIN] NVARCHAR(30) UNIQUE NOT NULL,
	[ROLE_ID] INT NOT NULL,
	PRIMARY KEY ([ID]),
	FOREIGN KEY ([ROLE_ID]) REFERENCES [ROLE]([ID])
);

CREATE TABLE [BRAND]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(50) UNIQUE NOT NULL,
	PRIMARY KEY ([ID])
);

CREATE TABLE [VEHICL_TYPE]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(50) NOT NULL,
	PRIMARY KEY ([ID])
);

CREATE TABLE [ENGINE]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[VOLUME] INT NOT NULL,
	PRIMARY KEY ([ID])
);

CREATE TABLE [FUEL]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(10) UNIQUE NOT NULL,
	PRIMARY KEY ([ID])
);

CREATE TABLE [ENGINE_FUEL]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[ENGINE_ID] INT NOT NULL,
	[FUEL_ID] INT NOT NULL,
	PRIMARY KEY ([ID]),
	FOREIGN KEY ([ENGINE_ID]) REFERENCES ENGINE([ID]),
	FOREIGN KEY ([FUEL_ID]) REFERENCES FUEL([ID]),
	UNIQUE ([ENGINE_ID], [FUEL_ID])

);

CREATE TABLE [TRANSMISSION_TYPE]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(30) UNIQUE NOT NULL,
	PRIMARY KEY ([ID]),
);

CREATE TABLE [VEHICL]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[BRAND_ID] INT NOT NULL,
	[VEHICL_TYPE_ID] INT NOT NULL,
	[ENGINE_ID] INT NOT NULL,
	[TRANSMISSION_TYPE_ID] INT NOT NULL,
	PRIMARY KEY ([ID]),
	FOREIGN KEY ([BRAND_ID]) REFERENCES [BRAND]([ID]),
	FOREIGN KEY ([VEHICL_TYPE_ID]) REFERENCES [VEHICL_TYPE]([ID]),
	FOREIGN KEY ([ENGINE_ID]) REFERENCES [ENGINE]([ID]),
	FOREIGN KEY ([TRANSMISSION_TYPE_ID]) REFERENCES [TRANSMISSION_TYPE]([ID]),
	UNIQUE ([BRAND_ID], [VEHICL_TYPE_ID], [ENGINE_ID], [TRANSMISSION_TYPE_ID])
);

CREATE TABLE [ADVERTISEMENT]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[IS_ACTIVE] BIT NOT NULL,
	[EXPIRATION_DATE] DATETIME NOT NULL,
	[CREATED_DATE] DATETIME NOT NULL,
	[VEHICL_ID] INT NOT NULL,
	[USER_ID] INT NOT NULL,
	[REGION_ID] INT NOT NULL,
	PRIMARY KEY ([ID]),
	FOREIGN KEY ([USER_ID]) REFERENCES [USER]([ID]),
	FOREIGN KEY ([VEHICL_ID]) REFERENCES VEHICL([ID]),
	FOREIGN KEY ([REGION_ID]) REFERENCES REGION([ID])
);

GO

