--CREATE DATABASE CarsSale;

USE CarsSale

GO

CREATE TABLE [User](
    [Id] INT IDENTITY(1,1) NOT NULL,
	[UserName] NVARCHAR(50) NOT NULL,
    [Email] NVARCHAR(256) NULL,
    [EmailConfirmed] BIT NOT NULL,
    [Password] NVARCHAR(max) NULL,
    [SecurityStamp] NVARCHAR(max) NULL,
    [PhoneNumber] NVARCHAR(max) NULL,
    [PhoneNumberConfirmed] BIT NOT NULL,
    [TwoFactorEnabled] BIT NOT NULL,
    [LockoutEndDateUtc] DATETIME NULL,
    [LockoutEnabled] BIT NOT NULL,
    [AccessFailedCount] INT NOT NULL,
	/*Not Identity required*/
	[FullName] NVARCHAR(256) NOT NULL,
	[Birthday] DATETIME NULL,
	/***********************/
	PRIMARY KEY([Id]),
	UNIQUE ([UserName])
);

CREATE TABLE [Role](
    [Id] INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(256) NOT NULL,
	PRIMARY KEY([Id])
);

CREATE TABLE [UserRole](
    [UserId] INT NOT NULL,
    [RoleId] INT NOT NULL,
	FOREIGN KEY ([UserId]) REFERENCES [User]([Id]),
	FOREIGN KEY ([RoleId]) REFERENCES [Role]([Id])
);

CREATE TABLE [UserClaim](
    [Id] INT IDENTITY(1,1) NOT NULL,
    [UserId] INT NOT NULL,
    [ClaimType] NVARCHAR(max) NULL,
    [ClaimValue] NVARCHAR(max) NULL
	PRIMARY KEY([ID])
	FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
);

CREATE TABLE [UserLogin](
    [LoginProvider] NVARCHAR(128) NOT NULL,
    [ProviderKey] NVARCHAR(128) NOT NULL,
    [UserId] INT NOT NULL
	FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
);

CREATE TABLE [REGION]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(50) UNIQUE NOT NULL,
	PRIMARY KEY ([ID])
);


CREATE TABLE [BRAND]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(50) UNIQUE NOT NULL,
	PRIMARY KEY ([ID])
);

CREATE TABLE [VEHICL_TYPE]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(50) NOT NULL,
	PRIMARY KEY ([ID])
);

CREATE TABLE [ENGINE]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[VOLUME] INT NOT NULL,
	PRIMARY KEY ([ID])
);

CREATE TABLE [FUEL]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(10) UNIQUE NOT NULL,
	PRIMARY KEY ([ID])
);

CREATE TABLE [ENGINE_FUEL]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[ENGINE_ID] INT NOT NULL,
	[FUEL_ID] INT NOT NULL,
	PRIMARY KEY ([ID]),
	FOREIGN KEY ([ENGINE_ID]) REFERENCES ENGINE([ID]),
	FOREIGN KEY ([FUEL_ID]) REFERENCES FUEL([ID]),
	UNIQUE ([ENGINE_ID], [FUEL_ID])

);

CREATE TABLE [TRANSMISSION_TYPE]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[NAME] NVARCHAR(30) UNIQUE NOT NULL,
	PRIMARY KEY ([ID]),
);

CREATE TABLE [CURRENCY](
    [ID] INT IDENTITY(1,1) NOT NULL,
    [CODE] NVARCHAR(256) NOT NULL,
	[SIGN] NVARCHAR(5) NOT NULL,
	UNIQUE ([CODE], [SIGN]),
	PRIMARY KEY([ID])
);

CREATE TABLE [VEHICL]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[BRAND_ID] INT NOT NULL,
	[VEHICL_TYPE_ID] INT NOT NULL,
	[ENGINE_ID] INT NOT NULL,
	[TRANSMISSION_TYPE_ID] INT NOT NULL,
	PRIMARY KEY ([ID]),
	FOREIGN KEY ([BRAND_ID]) REFERENCES [BRAND]([ID]),
	FOREIGN KEY ([VEHICL_TYPE_ID]) REFERENCES [VEHICL_TYPE]([ID]),
	FOREIGN KEY ([ENGINE_ID]) REFERENCES [ENGINE]([ID]),
	FOREIGN KEY ([TRANSMISSION_TYPE_ID]) REFERENCES [TRANSMISSION_TYPE]([ID]),
	UNIQUE ([BRAND_ID], [VEHICL_TYPE_ID], [ENGINE_ID], [TRANSMISSION_TYPE_ID])
);

CREATE TABLE [ADVERTISEMENT]
(
	[ID] INT IDENTITY(1, 1) NOT NULL,
	[IS_ACTIVE] BIT NOT NULL,
	[EXPIRATION_DATE] DATETIME NOT NULL,
	[CREATED_DATE] DATETIME NOT NULL,
	[VEHICL_ID] INT NOT NULL,
	[CURRENCY_ID] INT NOT NULL,
	[PRICE] INT NOT NULL,
	[USER_ID] INT NOT NULL,
	[REGION_ID] INT NOT NULL,
	[IMAGE_PATH] NVARCHAR(256) NOT NULL,
	PRIMARY KEY ([ID]),
	FOREIGN KEY ([USER_ID]) REFERENCES [USER]([ID]),
	FOREIGN KEY ([VEHICL_ID]) REFERENCES VEHICL([ID]),
	FOREIGN KEY ([REGION_ID]) REFERENCES REGION([ID]),
	FOREIGN KEY ([CURRENCY_ID]) REFERENCES [CURRENCY]([ID]),
);

GO

