//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsSale.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVERTISEMENT
    {
        public int ID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public System.DateTime EXPIRATION_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int VEHICL_ID { get; set; }
        public int USER_ID { get; set; }
        public int REGION_ID { get; set; }
    
        public virtual REGION REGION { get; set; }
        public virtual USER USER { get; set; }
        public virtual VEHICL VEHICL { get; set; }
    }
}
